export const categories = {
    JAVA: "Java",
    NODE_JS: "Node.js",
    JAVA_SCRIPT: "JavaScript",
    REACT: "React.js",
    ANGULAR: "Angular",
    POSTGRESQL: "PostgreSQL",
    MONGODB: "MongoDB",
    SPRING_FRAMEWORK: "Spring Framework",
    HTML: "HTML5",
    CSS: "CSS3",
    IOS: "iOS",
    ANDROID: "Android",
    FLUTTER: "Flutter",
    RUBY: "Ruby",
    ELASTICSEARCH: "ElasticSearch",
    REDIS: "RedisMQ",
    GO: "Golang",
    SALESFORCE: "Salesforce",
    QA_MANUAL: "QA Manual",
    QA_AUTOMATION: "QA Automation",
    UI_UX: "UI/UX Design",
    FACEBOOK_ADS: "Facebook ADS",
    GOOGLE_ADS: "Google ADS",
    PROJECT_MANAGER: "Project Manager",
    SMM: "SMM",
    DEVOPS: "DevOps",
    PHP: "PHP",
    LARAVEL: "Laravel",
    TYPE_SCRIPT: "TypeScript",
    KOTLIN: "Kotlin",
    RUST: "Rust",
    RAILS: "Rails",
    VUE: "Vue.js",
    AWS: "Amazon Web Services",
    NEST: "Nest.js",
    EXPRESS: "Express.js",
    DOCKER: "Docker",
    REDUX: "Redux",
    C: "C/C++",
    NUXT: "Nuxt.js",
    NEXT: "Next.js",
    WORDPRESS: "WordPress",
    RXJS: "RxJS",
    REACT_NATIVE: "React Native"
}